from glob import glob
from os.path import basename
from os import system
import pandas as pd
import os.path
from numpy import log2
import gzip
from datetime import datetime

configfile: "config/config.yaml"

if config["protein_only"] == True:
    include: "rules/braker2_protein.smk"

elif config["rnaseq_format"] in ["bam","fastq"]:
    sampleinfo = pd.read_table(config["sampleTable"])
    SAMPLES=list(sampleinfo.loc[:,"sampleid"])

    if config["rnaseq_format"] == "bam":
        BAMS=list(sampleinfo.loc[:,"bam"])
        include: "rules/braker3_bams.smk"

    elif config["rnaseq_format"] == "fastq":
        include: "rules/star.smk"
        include: "rules/starindex.smk"
        include: "rules/braker3_fastq.smk"

    else:
        raise ValueError("input rna-seq data type not among supported types: bam, fastq")

else:
    raise ValueError("incorrect or missing value in config/config.yaml")

rule all:
        input:
            "results/braker3/braker/braker.gtf"
        default_target: True

include: "rules/brakermover.smk"
