
########################
## RNA-SEQ FASTQ FILES #
########################


## path to singularity image ##
brakersif: "braker3.sif"

## species ##
species: "dmel_eval"

## table of sample IDs from which to derive ID strings for fastq files ##
sampleTable: "sampletable.tsv"

## Genome ##
genome: "data/headercleaned_GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna"

## path to OrthoDB protein fasta ##
orthodb: "data/orthoDBv100_arthropoda.fasta"


## data format ##
rnaseq_format: "bam"

## directory containing fastq files ""
fastqDir: ""

## directory containing bam files ##
bamdir: "data/bams/"
