
########################
## RNA-SEQ FASTQ FILES #
########################


## path to singularity image ##
brakersif: "braker3.sif"

## species ##
#put a name here for your species that DOES NOT match an existing AUGUSTUS species name
species: "" 

## table of sample IDs from which to derive ID strings for fastq files ##
sampleTable: "samplesheet.tsv"

## Genome ##
# path to soft-masked genome fasta
genome: ""

## path to OrthoDB protein fasta ##
orthodb: ""


## data format ##
rnaseq_format: "" # available options are bam and fastq

## directory containing fastq files ""
fastqDir: "data/fastq/"

## directory containing bam files ##
bamdir: "data/bams/"
