
########################
## RNA-SEQ FASTQ FILES #
########################


## path to singularity image ##
brakersif: ""

## species ##
species: ""

## table of sample IDs from which to derive ID strings for fastq files ##
sampleTable: ""

## Genome ##
genome: ""

## path to OrthoDB protein fasta ##
orthodb: ""


## data format ##
rnaseq_format: "bam"

## directory containing fastq files ""
fastqDir: ""

## directory containing bam files ##
bamdir: "data/bams/"
