executor: slurm
use-conda: True
jobs: 100
latency-wait: 100
retries: 0

set-threads:
    braker3_bams: 48

set-resources:
    braker3_bams:
        nodes: 1
        mem_mb: 96000
        slurm_partition: "shared,unrestricted"
        runtime: 360  #"72:00:00"
