#executor: slurm
#use-conda: True
#jobs: 100
#latency-wait: 100
#retries: 0

set-threads:
    braker3_bams: 48

set-resources:
    braker3_bams:
        nodes: 1
        tasks: 1
        cpus_per_task: 48
        mem_mb: 96000
        runtime: "48h" # this setting allocates 48 hours, adjust as needed
